/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/content/content';
import * as import13 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import14 from 'ionic-angular/config/config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'ionic-angular/components/app/app';
import * as import17 from 'ionic-angular/util/keyboard';
import * as import18 from '@angular/core/src/zone/ng_zone';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from 'ionic-angular/components/tabs/tabs';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Http));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import11.ComponentFactory<import3.HomePage> = new import11.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import12.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _text_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _text_131:any;
  _el_132:any;
  _text_133:any;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _text_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _text_141:any;
  _el_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _el_146:any;
  _text_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _text_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _el_155:any;
  _text_156:any;
  _el_157:any;
  _text_158:any;
  _el_159:any;
  _text_160:any;
  _el_161:any;
  _text_162:any;
  _text_163:any;
  _text_164:any;
  _el_165:any;
  _text_166:any;
  _el_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _text_171:any;
  _text_172:any;
  _el_173:any;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _el_177:any;
  _text_178:any;
  _text_179:any;
  _text_180:any;
  _el_181:any;
  _text_182:any;
  _el_183:any;
  _text_184:any;
  _el_185:any;
  _text_186:any;
  _text_187:any;
  _text_188:any;
  _el_189:any;
  _text_190:any;
  _el_191:any;
  _text_192:any;
  _el_193:any;
  _text_194:any;
  _text_195:any;
  _text_196:any;
  _el_197:any;
  _text_198:any;
  _el_199:any;
  _text_200:any;
  _el_201:any;
  _text_202:any;
  _text_203:any;
  _text_204:any;
  _el_205:any;
  _text_206:any;
  _el_207:any;
  _text_208:any;
  _el_209:any;
  _text_210:any;
  _text_211:any;
  _text_212:any;
  _el_213:any;
  _text_214:any;
  _el_215:any;
  _text_216:any;
  _el_217:any;
  _text_218:any;
  _text_219:any;
  _text_220:any;
  _text_221:any;
  _text_222:any;
  _text_223:any;
  _text_224:any;
  _el_225:any;
  _text_226:any;
  _el_227:any;
  _text_228:any;
  _el_229:any;
  _text_230:any;
  _el_231:any;
  _text_232:any;
  _text_233:any;
  _text_234:any;
  _el_235:any;
  _text_236:any;
  _el_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _text_241:any;
  _text_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _el_246:any;
  _text_247:any;
  _el_248:any;
  _text_249:any;
  _el_250:any;
  _text_251:any;
  _el_252:any;
  _text_253:any;
  _text_254:any;
  _el_255:any;
  _text_256:any;
  _text_257:any;
  _el_258:any;
  _text_259:any;
  _text_260:any;
  _text_261:any;
  _el_262:any;
  _text_263:any;
  _el_264:any;
  _text_265:any;
  _el_266:any;
  _text_267:any;
  _text_268:any;
  _text_269:any;
  _text_270:any;
  _text_271:any;
  _el_272:any;
  _text_273:any;
  _el_274:any;
  _text_275:any;
  _el_276:any;
  _text_277:any;
  _el_278:any;
  _text_279:any;
  _el_280:any;
  _text_281:any;
  _text_282:any;
  _el_283:any;
  _text_284:any;
  _text_285:any;
  _el_286:any;
  _text_287:any;
  _text_288:any;
  _text_289:any;
  _el_290:any;
  _text_291:any;
  _el_292:any;
  _text_293:any;
  _el_294:any;
  _text_295:any;
  _text_296:any;
  _text_297:any;
  _text_298:any;
  _text_299:any;
  _el_300:any;
  _text_301:any;
  _el_302:any;
  _text_303:any;
  _el_304:any;
  _text_305:any;
  _el_306:any;
  _text_307:any;
  _el_308:any;
  _text_309:any;
  _text_310:any;
  _el_311:any;
  _text_312:any;
  _text_313:any;
  _el_314:any;
  _text_315:any;
  _text_316:any;
  _text_317:any;
  _el_318:any;
  _text_319:any;
  _el_320:any;
  _text_321:any;
  _el_322:any;
  _text_323:any;
  _text_324:any;
  _text_325:any;
  _text_326:any;
  _text_327:any;
  _el_328:any;
  _text_329:any;
  _el_330:any;
  _text_331:any;
  _el_332:any;
  _text_333:any;
  _el_334:any;
  _text_335:any;
  _el_336:any;
  _text_337:any;
  _text_338:any;
  _el_339:any;
  _text_340:any;
  _text_341:any;
  _el_342:any;
  _text_343:any;
  _text_344:any;
  _text_345:any;
  _el_346:any;
  _text_347:any;
  _el_348:any;
  _text_349:any;
  _el_350:any;
  _text_351:any;
  _text_352:any;
  _text_353:any;
  _text_354:any;
  _text_355:any;
  _text_356:any;
  _text_357:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import13.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import12.Content(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import16.App),this.parentInjector.get(import17.Keyboard),this.parentInjector.get(import18.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import20.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'section',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','home-page');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','swiper-container');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','swiper-wrapper');
    this._text_7 = this.renderer.createText(this._el_6,'\n\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','swiper-slide');
    this._text_9 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'img',(null as any));
    this.renderer.setElementAttribute(this._el_10,'src','assets/img2/home_banner_1.jpeg');
    this._text_11 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','swiper-slide');
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'img',(null as any));
    this.renderer.setElementAttribute(this._el_15,'src','assets/img2/home_banner_2.jpeg');
    this._text_16 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','swiper-slide');
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'img',(null as any));
    this.renderer.setElementAttribute(this._el_20,'src','assets/img2/home_banner_3.jpeg');
    this._text_21 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','swiper-slide');
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'img',(null as any));
    this.renderer.setElementAttribute(this._el_25,'src','assets/img2/home_banner_4.jpeg');
    this._text_26 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','swiper-pagination');
    this._text_31 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_2,'section',(null as any));
    this.renderer.setElementAttribute(this._el_34,'id','home_menu');
    this._text_35 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','home_menu_list');
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'img',(null as any));
    this.renderer.setElementAttribute(this._el_38,'src','assets/icon/home/m1.png');
    this._text_39 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_36,'p',(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'菜谱分类',(null as any));
    this._text_42 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_43 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','home_menu_list');
    this._text_45 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'img',(null as any));
    this.renderer.setElementAttribute(this._el_46,'src','assets/icon/home/m2.png');
    this._text_47 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_44,'p',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'视频',(null as any));
    this._text_50 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','home_menu_list');
    this._text_53 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'img',(null as any));
    this.renderer.setElementAttribute(this._el_54,'src','assets/icon/home/m3.png');
    this._text_55 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_52,'p',(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'养生头条',(null as any));
    this._text_58 = this.renderer.createText(this._el_52,'\n            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','home_menu_list');
    this._text_61 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'img',(null as any));
    this.renderer.setElementAttribute(this._el_62,'src','assets/icon/home/m4.png');
    this._text_63 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_60,'p',(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'工具分类',(null as any));
    this._text_66 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_2,'section',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','home_hot');
    this._text_71 = this.renderer.createText(this._el_70,'\n            ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_70,'div',(null as any));
    this.renderer.setElementAttribute(this._el_72,'class','home_hot_title');
    this._text_73 = this.renderer.createText(this._el_72,'\n                ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_72,'p',(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'最热头条',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'\n                ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_72,'img',(null as any));
    this.renderer.setElementAttribute(this._el_77,'src','assets/icon/home/hot_more.png');
    this._text_78 = this.renderer.createText(this._el_72,'\n            ',(null as any));
    this._text_79 = this.renderer.createText(this._el_70,'\n            ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_70,'div',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','home_hot_list');
    this._text_81 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','home_hot_item_img');
    this._text_83 = this.renderer.createText(this._el_82,'\n                    ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'img',(null as any));
    this.renderer.setElementAttribute(this._el_84,'src','assets/img2/hot_1.jpeg');
    this._text_85 = this.renderer.createText(this._el_82,'\n                ',(null as any));
    this._text_86 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_87,'class','home_hot_item');
    this._text_88 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_87,'p',(null as any));
    this.renderer.setElementAttribute(this._el_89,'class','home_hot_item_title');
    this._text_90 = this.renderer.createText(this._el_89,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_91 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_87,'p',(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'浏览数：100',(null as any));
    this._text_94 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_87,'p',(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'10-22',(null as any));
    this._text_97 = this.renderer.createText(this._el_87,'\n                ',(null as any));
    this._text_98 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._text_99 = this.renderer.createText(this._el_70,'\n            ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_70,'div',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','home_hot_list');
    this._text_101 = this.renderer.createText(this._el_100,'\n                ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_100,'div',(null as any));
    this.renderer.setElementAttribute(this._el_102,'class','home_hot_item_img');
    this._text_103 = this.renderer.createText(this._el_102,'\n                    ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_102,'img',(null as any));
    this.renderer.setElementAttribute(this._el_104,'src','assets/img2/hot_2.jpeg');
    this._text_105 = this.renderer.createText(this._el_102,'\n                ',(null as any));
    this._text_106 = this.renderer.createText(this._el_100,'\n                ',(null as any));
    this._el_107 = this.renderer.createElement(this._el_100,'div',(null as any));
    this.renderer.setElementAttribute(this._el_107,'class','home_hot_item');
    this._text_108 = this.renderer.createText(this._el_107,'\n                    ',(null as any));
    this._el_109 = this.renderer.createElement(this._el_107,'p',(null as any));
    this.renderer.setElementAttribute(this._el_109,'class','home_hot_item_title');
    this._text_110 = this.renderer.createText(this._el_109,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_111 = this.renderer.createText(this._el_107,'\n                    ',(null as any));
    this._el_112 = this.renderer.createElement(this._el_107,'p',(null as any));
    this._text_113 = this.renderer.createText(this._el_112,'浏览数：100',(null as any));
    this._text_114 = this.renderer.createText(this._el_107,'\n                    ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_107,'p',(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'10-22',(null as any));
    this._text_117 = this.renderer.createText(this._el_107,'\n                ',(null as any));
    this._text_118 = this.renderer.createText(this._el_100,'\n            ',(null as any));
    this._text_119 = this.renderer.createText(this._el_70,'\n            ',(null as any));
    this._el_120 = this.renderer.createElement(this._el_70,'div',(null as any));
    this.renderer.setElementAttribute(this._el_120,'class','home_hot_list');
    this._text_121 = this.renderer.createText(this._el_120,'\n                ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_120,'div',(null as any));
    this.renderer.setElementAttribute(this._el_122,'class','home_hot_item_img');
    this._text_123 = this.renderer.createText(this._el_122,'\n                    ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_122,'img',(null as any));
    this.renderer.setElementAttribute(this._el_124,'src','assets/img2/hot_3.jpeg');
    this._text_125 = this.renderer.createText(this._el_122,'\n                ',(null as any));
    this._text_126 = this.renderer.createText(this._el_120,'\n                ',(null as any));
    this._el_127 = this.renderer.createElement(this._el_120,'div',(null as any));
    this.renderer.setElementAttribute(this._el_127,'class','home_hot_item');
    this._text_128 = this.renderer.createText(this._el_127,'\n                    ',(null as any));
    this._el_129 = this.renderer.createElement(this._el_127,'p',(null as any));
    this.renderer.setElementAttribute(this._el_129,'class','home_hot_item_title');
    this._text_130 = this.renderer.createText(this._el_129,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_131 = this.renderer.createText(this._el_127,'\n                    ',(null as any));
    this._el_132 = this.renderer.createElement(this._el_127,'p',(null as any));
    this._text_133 = this.renderer.createText(this._el_132,'浏览数：100',(null as any));
    this._text_134 = this.renderer.createText(this._el_127,'\n                    ',(null as any));
    this._el_135 = this.renderer.createElement(this._el_127,'p',(null as any));
    this._text_136 = this.renderer.createText(this._el_135,'10-22',(null as any));
    this._text_137 = this.renderer.createText(this._el_127,'\n                ',(null as any));
    this._text_138 = this.renderer.createText(this._el_120,'\n            ',(null as any));
    this._text_139 = this.renderer.createText(this._el_70,'\n        ',(null as any));
    this._text_140 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_141 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_142 = this.renderer.createElement(this._el_2,'section',(null as any));
    this.renderer.setElementAttribute(this._el_142,'class','home_hot_man');
    this._text_143 = this.renderer.createText(this._el_142,'\n            ',(null as any));
    this._el_144 = this.renderer.createElement(this._el_142,'div',(null as any));
    this.renderer.setElementAttribute(this._el_144,'class','home_hot_title');
    this._text_145 = this.renderer.createText(this._el_144,'\n                ',(null as any));
    this._el_146 = this.renderer.createElement(this._el_144,'p',(null as any));
    this._text_147 = this.renderer.createText(this._el_146,'人气推荐',(null as any));
    this._text_148 = this.renderer.createText(this._el_144,'\n                ',(null as any));
    this._el_149 = this.renderer.createElement(this._el_144,'img',(null as any));
    this.renderer.setElementAttribute(this._el_149,'src','assets/icon/home/hot_more.png');
    this._text_150 = this.renderer.createText(this._el_144,'\n            ',(null as any));
    this._text_151 = this.renderer.createText(this._el_142,'\n            ',(null as any));
    this._text_152 = this.renderer.createText(this._el_142,'\n            ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_142,'div',(null as any));
    this.renderer.setElementAttribute(this._el_153,'class','swiper-container-user');
    this._text_154 = this.renderer.createText(this._el_153,'\n                ',(null as any));
    this._el_155 = this.renderer.createElement(this._el_153,'div',(null as any));
    this.renderer.setElementAttribute(this._el_155,'class','swiper-wrapper');
    this._text_156 = this.renderer.createText(this._el_155,'\n\n                    ',(null as any));
    this._el_157 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_157,'class','swiper-slide');
    this._text_158 = this.renderer.createText(this._el_157,'\n                        ',(null as any));
    this._el_159 = this.renderer.createElement(this._el_157,'img',(null as any));
    this.renderer.setElementAttribute(this._el_159,'src','assets/img2/user_1.jpeg');
    this._text_160 = this.renderer.createText(this._el_157,'\n                        ',(null as any));
    this._el_161 = this.renderer.createElement(this._el_157,'p',(null as any));
    this._text_162 = this.renderer.createText(this._el_161,'萧冰xiaobing',(null as any));
    this._text_163 = this.renderer.createText(this._el_157,'\n                    ',(null as any));
    this._text_164 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_165 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_165,'class','swiper-slide');
    this._text_166 = this.renderer.createText(this._el_165,'\n                        ',(null as any));
    this._el_167 = this.renderer.createElement(this._el_165,'img',(null as any));
    this.renderer.setElementAttribute(this._el_167,'src','assets/img2/user_2.jpeg');
    this._text_168 = this.renderer.createText(this._el_165,'\n                        ',(null as any));
    this._el_169 = this.renderer.createElement(this._el_165,'p',(null as any));
    this._text_170 = this.renderer.createText(this._el_169,'毓玲珑',(null as any));
    this._text_171 = this.renderer.createText(this._el_165,'\n                    ',(null as any));
    this._text_172 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_173 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_173,'class','swiper-slide');
    this._text_174 = this.renderer.createText(this._el_173,'\n                        ',(null as any));
    this._el_175 = this.renderer.createElement(this._el_173,'img',(null as any));
    this.renderer.setElementAttribute(this._el_175,'src','assets/img2/user_3.jpeg');
    this._text_176 = this.renderer.createText(this._el_173,'\n                        ',(null as any));
    this._el_177 = this.renderer.createElement(this._el_173,'p',(null as any));
    this._text_178 = this.renderer.createText(this._el_177,'徐徐徐萌萌',(null as any));
    this._text_179 = this.renderer.createText(this._el_173,'\n                    ',(null as any));
    this._text_180 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_181 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_181,'class','swiper-slide');
    this._text_182 = this.renderer.createText(this._el_181,'\n                        ',(null as any));
    this._el_183 = this.renderer.createElement(this._el_181,'img',(null as any));
    this.renderer.setElementAttribute(this._el_183,'src','assets/img2/user_4.jpeg');
    this._text_184 = this.renderer.createText(this._el_181,'\n                        ',(null as any));
    this._el_185 = this.renderer.createElement(this._el_181,'p',(null as any));
    this._text_186 = this.renderer.createText(this._el_185,'春燕_Lsg6',(null as any));
    this._text_187 = this.renderer.createText(this._el_181,'\n                    ',(null as any));
    this._text_188 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_189 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_189,'class','swiper-slide');
    this._text_190 = this.renderer.createText(this._el_189,'\n                        ',(null as any));
    this._el_191 = this.renderer.createElement(this._el_189,'img',(null as any));
    this.renderer.setElementAttribute(this._el_191,'src','assets/img2/user_1.jpeg');
    this._text_192 = this.renderer.createText(this._el_189,'\n                        ',(null as any));
    this._el_193 = this.renderer.createElement(this._el_189,'p',(null as any));
    this._text_194 = this.renderer.createText(this._el_193,'萧冰xiaobing',(null as any));
    this._text_195 = this.renderer.createText(this._el_189,'\n                    ',(null as any));
    this._text_196 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_197 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_197,'class','swiper-slide');
    this._text_198 = this.renderer.createText(this._el_197,'\n                        ',(null as any));
    this._el_199 = this.renderer.createElement(this._el_197,'img',(null as any));
    this.renderer.setElementAttribute(this._el_199,'src','assets/img2/user_2.jpeg');
    this._text_200 = this.renderer.createText(this._el_197,'\n                        ',(null as any));
    this._el_201 = this.renderer.createElement(this._el_197,'p',(null as any));
    this._text_202 = this.renderer.createText(this._el_201,'毓玲珑',(null as any));
    this._text_203 = this.renderer.createText(this._el_197,'\n                    ',(null as any));
    this._text_204 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_205 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_205,'class','swiper-slide');
    this._text_206 = this.renderer.createText(this._el_205,'\n                        ',(null as any));
    this._el_207 = this.renderer.createElement(this._el_205,'img',(null as any));
    this.renderer.setElementAttribute(this._el_207,'src','assets/img2/user_3.jpeg');
    this._text_208 = this.renderer.createText(this._el_205,'\n                        ',(null as any));
    this._el_209 = this.renderer.createElement(this._el_205,'p',(null as any));
    this._text_210 = this.renderer.createText(this._el_209,'徐徐徐萌萌',(null as any));
    this._text_211 = this.renderer.createText(this._el_205,'\n                    ',(null as any));
    this._text_212 = this.renderer.createText(this._el_155,'\n                    ',(null as any));
    this._el_213 = this.renderer.createElement(this._el_155,'div',(null as any));
    this.renderer.setElementAttribute(this._el_213,'class','swiper-slide');
    this._text_214 = this.renderer.createText(this._el_213,'\n                        ',(null as any));
    this._el_215 = this.renderer.createElement(this._el_213,'img',(null as any));
    this.renderer.setElementAttribute(this._el_215,'src','assets/img2/user_4.jpeg');
    this._text_216 = this.renderer.createText(this._el_213,'\n                        ',(null as any));
    this._el_217 = this.renderer.createElement(this._el_213,'p',(null as any));
    this._text_218 = this.renderer.createText(this._el_217,'春燕_Lsg6',(null as any));
    this._text_219 = this.renderer.createText(this._el_213,'\n                    ',(null as any));
    this._text_220 = this.renderer.createText(this._el_155,'\n\n                ',(null as any));
    this._text_221 = this.renderer.createText(this._el_153,'\n\n            ',(null as any));
    this._text_222 = this.renderer.createText(this._el_142,'\n        ',(null as any));
    this._text_223 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_224 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_225 = this.renderer.createElement(this._el_2,'section',(null as any));
    this.renderer.setElementAttribute(this._el_225,'class','home_class');
    this._text_226 = this.renderer.createText(this._el_225,'\n            ',(null as any));
    this._el_227 = this.renderer.createElement(this._el_225,'img',(null as any));
    this.renderer.setElementAttribute(this._el_227,'src','assets/img2/home_ad_1.jpeg');
    this._text_228 = this.renderer.createText(this._el_225,'\n            ',(null as any));
    this._el_229 = this.renderer.createElement(this._el_225,'img',(null as any));
    this.renderer.setElementAttribute(this._el_229,'src','assets/img2/home_ad_2.png');
    this._text_230 = this.renderer.createText(this._el_225,'\n            ',(null as any));
    this._el_231 = this.renderer.createElement(this._el_225,'img',(null as any));
    this.renderer.setElementAttribute(this._el_231,'src','assets/img2/home_ad_3.png');
    this._text_232 = this.renderer.createText(this._el_225,'\n        ',(null as any));
    this._text_233 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_234 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_235 = this.renderer.createElement(this._el_2,'section',(null as any));
    this.renderer.setElementAttribute(this._el_235,'class','home_works');
    this._text_236 = this.renderer.createText(this._el_235,'\n            ',(null as any));
    this._el_237 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_237,'class','home_hot_title');
    this._text_238 = this.renderer.createText(this._el_237,'\n                ',(null as any));
    this._el_239 = this.renderer.createElement(this._el_237,'p',(null as any));
    this._text_240 = this.renderer.createText(this._el_239,'最新佳作',(null as any));
    this._text_241 = this.renderer.createText(this._el_237,'\n            ',(null as any));
    this._text_242 = this.renderer.createText(this._el_235,'\n            ',(null as any));
    this._text_243 = this.renderer.createText(this._el_235,'\n            ',(null as any));
    this._el_244 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_244,'class','home_work_list');
    this._text_245 = this.renderer.createText(this._el_244,'\n                ',(null as any));
    this._el_246 = this.renderer.createElement(this._el_244,'img',(null as any));
    this.renderer.setElementAttribute(this._el_246,'src','assets/img2/home_work_1.jpeg');
    this._text_247 = this.renderer.createText(this._el_244,'\n                ',(null as any));
    this._el_248 = this.renderer.createElement(this._el_244,'div',(null as any));
    this.renderer.setElementAttribute(this._el_248,'class','home_work_cont');
    this._text_249 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_250 = this.renderer.createElement(this._el_248,'div',(null as any));
    this.renderer.setElementAttribute(this._el_250,'class','home_work_cont_left');
    this._text_251 = this.renderer.createText(this._el_250,'\n                        ',(null as any));
    this._el_252 = this.renderer.createElement(this._el_250,'p',(null as any));
    this.renderer.setElementAttribute(this._el_252,'class','home_work_cont_left_title');
    this._text_253 = this.renderer.createText(this._el_252,'蚝油鸡胸肉',(null as any));
    this._text_254 = this.renderer.createText(this._el_250,'\n                        ',(null as any));
    this._el_255 = this.renderer.createElement(this._el_250,'p',(null as any));
    this._text_256 = this.renderer.createText(this._el_255,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_257 = this.renderer.createText(this._el_250,'\n                        ',(null as any));
    this._el_258 = this.renderer.createElement(this._el_250,'p',(null as any));
    this._text_259 = this.renderer.createText(this._el_258,'10-22',(null as any));
    this._text_260 = this.renderer.createText(this._el_250,'\n                    ',(null as any));
    this._text_261 = this.renderer.createText(this._el_248,'\n                    ',(null as any));
    this._el_262 = this.renderer.createElement(this._el_248,'div',(null as any));
    this.renderer.setElementAttribute(this._el_262,'class','home_work_cont_right');
    this._text_263 = this.renderer.createText(this._el_262,'\n                        ',(null as any));
    this._el_264 = this.renderer.createElement(this._el_262,'img',(null as any));
    this.renderer.setElementAttribute(this._el_264,'src','assets/img2/user_4.jpeg');
    this._text_265 = this.renderer.createText(this._el_262,'\n                        ',(null as any));
    this._el_266 = this.renderer.createElement(this._el_262,'p',(null as any));
    this._text_267 = this.renderer.createText(this._el_266,'春燕_Lsg6',(null as any));
    this._text_268 = this.renderer.createText(this._el_262,'\n                    ',(null as any));
    this._text_269 = this.renderer.createText(this._el_248,'\n                ',(null as any));
    this._text_270 = this.renderer.createText(this._el_244,'\n            ',(null as any));
    this._text_271 = this.renderer.createText(this._el_235,'\n            ',(null as any));
    this._el_272 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_272,'class','home_work_list');
    this._text_273 = this.renderer.createText(this._el_272,'\n                ',(null as any));
    this._el_274 = this.renderer.createElement(this._el_272,'img',(null as any));
    this.renderer.setElementAttribute(this._el_274,'src','assets/img2/home_work_2.jpeg');
    this._text_275 = this.renderer.createText(this._el_272,'\n                ',(null as any));
    this._el_276 = this.renderer.createElement(this._el_272,'div',(null as any));
    this.renderer.setElementAttribute(this._el_276,'class','home_work_cont');
    this._text_277 = this.renderer.createText(this._el_276,'\n                    ',(null as any));
    this._el_278 = this.renderer.createElement(this._el_276,'div',(null as any));
    this.renderer.setElementAttribute(this._el_278,'class','home_work_cont_left');
    this._text_279 = this.renderer.createText(this._el_278,'\n                        ',(null as any));
    this._el_280 = this.renderer.createElement(this._el_278,'p',(null as any));
    this.renderer.setElementAttribute(this._el_280,'class','home_work_cont_left_title');
    this._text_281 = this.renderer.createText(this._el_280,'蚝油鸡胸肉',(null as any));
    this._text_282 = this.renderer.createText(this._el_278,'\n                        ',(null as any));
    this._el_283 = this.renderer.createElement(this._el_278,'p',(null as any));
    this._text_284 = this.renderer.createText(this._el_283,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_285 = this.renderer.createText(this._el_278,'\n                        ',(null as any));
    this._el_286 = this.renderer.createElement(this._el_278,'p',(null as any));
    this._text_287 = this.renderer.createText(this._el_286,'10-22',(null as any));
    this._text_288 = this.renderer.createText(this._el_278,'\n                    ',(null as any));
    this._text_289 = this.renderer.createText(this._el_276,'\n                    ',(null as any));
    this._el_290 = this.renderer.createElement(this._el_276,'div',(null as any));
    this.renderer.setElementAttribute(this._el_290,'class','home_work_cont_right');
    this._text_291 = this.renderer.createText(this._el_290,'\n                        ',(null as any));
    this._el_292 = this.renderer.createElement(this._el_290,'img',(null as any));
    this.renderer.setElementAttribute(this._el_292,'src','assets/img2/user_3.jpeg');
    this._text_293 = this.renderer.createText(this._el_290,'\n                        ',(null as any));
    this._el_294 = this.renderer.createElement(this._el_290,'p',(null as any));
    this._text_295 = this.renderer.createText(this._el_294,'徐徐徐萌萌',(null as any));
    this._text_296 = this.renderer.createText(this._el_290,'\n                    ',(null as any));
    this._text_297 = this.renderer.createText(this._el_276,'\n                ',(null as any));
    this._text_298 = this.renderer.createText(this._el_272,'\n            ',(null as any));
    this._text_299 = this.renderer.createText(this._el_235,'\n            ',(null as any));
    this._el_300 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_300,'class','home_work_list');
    this._text_301 = this.renderer.createText(this._el_300,'\n                ',(null as any));
    this._el_302 = this.renderer.createElement(this._el_300,'img',(null as any));
    this.renderer.setElementAttribute(this._el_302,'src','assets/img2/home_work_3.jpeg');
    this._text_303 = this.renderer.createText(this._el_300,'\n                ',(null as any));
    this._el_304 = this.renderer.createElement(this._el_300,'div',(null as any));
    this.renderer.setElementAttribute(this._el_304,'class','home_work_cont');
    this._text_305 = this.renderer.createText(this._el_304,'\n                    ',(null as any));
    this._el_306 = this.renderer.createElement(this._el_304,'div',(null as any));
    this.renderer.setElementAttribute(this._el_306,'class','home_work_cont_left');
    this._text_307 = this.renderer.createText(this._el_306,'\n                        ',(null as any));
    this._el_308 = this.renderer.createElement(this._el_306,'p',(null as any));
    this.renderer.setElementAttribute(this._el_308,'class','home_work_cont_left_title');
    this._text_309 = this.renderer.createText(this._el_308,'蚝油鸡胸肉',(null as any));
    this._text_310 = this.renderer.createText(this._el_306,'\n                        ',(null as any));
    this._el_311 = this.renderer.createElement(this._el_306,'p',(null as any));
    this._text_312 = this.renderer.createText(this._el_311,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_313 = this.renderer.createText(this._el_306,'\n                        ',(null as any));
    this._el_314 = this.renderer.createElement(this._el_306,'p',(null as any));
    this._text_315 = this.renderer.createText(this._el_314,'10-22',(null as any));
    this._text_316 = this.renderer.createText(this._el_306,'\n                    ',(null as any));
    this._text_317 = this.renderer.createText(this._el_304,'\n                    ',(null as any));
    this._el_318 = this.renderer.createElement(this._el_304,'div',(null as any));
    this.renderer.setElementAttribute(this._el_318,'class','home_work_cont_right');
    this._text_319 = this.renderer.createText(this._el_318,'\n                        ',(null as any));
    this._el_320 = this.renderer.createElement(this._el_318,'img',(null as any));
    this.renderer.setElementAttribute(this._el_320,'src','assets/img2/user_2.jpeg');
    this._text_321 = this.renderer.createText(this._el_318,'\n                        ',(null as any));
    this._el_322 = this.renderer.createElement(this._el_318,'p',(null as any));
    this._text_323 = this.renderer.createText(this._el_322,'毓玲珑',(null as any));
    this._text_324 = this.renderer.createText(this._el_318,'\n                    ',(null as any));
    this._text_325 = this.renderer.createText(this._el_304,'\n                ',(null as any));
    this._text_326 = this.renderer.createText(this._el_300,'\n            ',(null as any));
    this._text_327 = this.renderer.createText(this._el_235,'\n            ',(null as any));
    this._el_328 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_328,'class','home_work_list');
    this._text_329 = this.renderer.createText(this._el_328,'\n                ',(null as any));
    this._el_330 = this.renderer.createElement(this._el_328,'img',(null as any));
    this.renderer.setElementAttribute(this._el_330,'src','assets/img2/home_work_1.jpeg');
    this._text_331 = this.renderer.createText(this._el_328,'\n                ',(null as any));
    this._el_332 = this.renderer.createElement(this._el_328,'div',(null as any));
    this.renderer.setElementAttribute(this._el_332,'class','home_work_cont');
    this._text_333 = this.renderer.createText(this._el_332,'\n                    ',(null as any));
    this._el_334 = this.renderer.createElement(this._el_332,'div',(null as any));
    this.renderer.setElementAttribute(this._el_334,'class','home_work_cont_left');
    this._text_335 = this.renderer.createText(this._el_334,'\n                        ',(null as any));
    this._el_336 = this.renderer.createElement(this._el_334,'p',(null as any));
    this.renderer.setElementAttribute(this._el_336,'class','home_work_cont_left_title');
    this._text_337 = this.renderer.createText(this._el_336,'蚝油鸡胸肉',(null as any));
    this._text_338 = this.renderer.createText(this._el_334,'\n                        ',(null as any));
    this._el_339 = this.renderer.createElement(this._el_334,'p',(null as any));
    this._text_340 = this.renderer.createText(this._el_339,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_341 = this.renderer.createText(this._el_334,'\n                        ',(null as any));
    this._el_342 = this.renderer.createElement(this._el_334,'p',(null as any));
    this._text_343 = this.renderer.createText(this._el_342,'10-22',(null as any));
    this._text_344 = this.renderer.createText(this._el_334,'\n                    ',(null as any));
    this._text_345 = this.renderer.createText(this._el_332,'\n                    ',(null as any));
    this._el_346 = this.renderer.createElement(this._el_332,'div',(null as any));
    this.renderer.setElementAttribute(this._el_346,'class','home_work_cont_right');
    this._text_347 = this.renderer.createText(this._el_346,'\n                        ',(null as any));
    this._el_348 = this.renderer.createElement(this._el_346,'img',(null as any));
    this.renderer.setElementAttribute(this._el_348,'src','assets/img2/user_1.jpeg');
    this._text_349 = this.renderer.createText(this._el_346,'\n                        ',(null as any));
    this._el_350 = this.renderer.createElement(this._el_346,'p',(null as any));
    this._text_351 = this.renderer.createText(this._el_350,'萧冰xiaobing',(null as any));
    this._text_352 = this.renderer.createText(this._el_346,'\n                    ',(null as any));
    this._text_353 = this.renderer.createText(this._el_332,'\n                ',(null as any));
    this._text_354 = this.renderer.createText(this._el_328,'\n            ',(null as any));
    this._text_355 = this.renderer.createText(this._el_235,'\n        ',(null as any));
    this._text_356 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_357 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_357
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_72,'click',this.eventHandler(this._handle_click_72_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_80,'click',this.eventHandler(this._handle_click_80_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_100,'click',this.eventHandler(this._handle_click_100_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_120,'click',this.eventHandler(this._handle_click_120_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._text_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._el_159,
      this._text_160,
      this._el_161,
      this._text_162,
      this._text_163,
      this._text_164,
      this._el_165,
      this._text_166,
      this._el_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._text_171,
      this._text_172,
      this._el_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._el_177,
      this._text_178,
      this._text_179,
      this._text_180,
      this._el_181,
      this._text_182,
      this._el_183,
      this._text_184,
      this._el_185,
      this._text_186,
      this._text_187,
      this._text_188,
      this._el_189,
      this._text_190,
      this._el_191,
      this._text_192,
      this._el_193,
      this._text_194,
      this._text_195,
      this._text_196,
      this._el_197,
      this._text_198,
      this._el_199,
      this._text_200,
      this._el_201,
      this._text_202,
      this._text_203,
      this._text_204,
      this._el_205,
      this._text_206,
      this._el_207,
      this._text_208,
      this._el_209,
      this._text_210,
      this._text_211,
      this._text_212,
      this._el_213,
      this._text_214,
      this._el_215,
      this._text_216,
      this._el_217,
      this._text_218,
      this._text_219,
      this._text_220,
      this._text_221,
      this._text_222,
      this._text_223,
      this._text_224,
      this._el_225,
      this._text_226,
      this._el_227,
      this._text_228,
      this._el_229,
      this._text_230,
      this._el_231,
      this._text_232,
      this._text_233,
      this._text_234,
      this._el_235,
      this._text_236,
      this._el_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._text_241,
      this._text_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._el_246,
      this._text_247,
      this._el_248,
      this._text_249,
      this._el_250,
      this._text_251,
      this._el_252,
      this._text_253,
      this._text_254,
      this._el_255,
      this._text_256,
      this._text_257,
      this._el_258,
      this._text_259,
      this._text_260,
      this._text_261,
      this._el_262,
      this._text_263,
      this._el_264,
      this._text_265,
      this._el_266,
      this._text_267,
      this._text_268,
      this._text_269,
      this._text_270,
      this._text_271,
      this._el_272,
      this._text_273,
      this._el_274,
      this._text_275,
      this._el_276,
      this._text_277,
      this._el_278,
      this._text_279,
      this._el_280,
      this._text_281,
      this._text_282,
      this._el_283,
      this._text_284,
      this._text_285,
      this._el_286,
      this._text_287,
      this._text_288,
      this._text_289,
      this._el_290,
      this._text_291,
      this._el_292,
      this._text_293,
      this._el_294,
      this._text_295,
      this._text_296,
      this._text_297,
      this._text_298,
      this._text_299,
      this._el_300,
      this._text_301,
      this._el_302,
      this._text_303,
      this._el_304,
      this._text_305,
      this._el_306,
      this._text_307,
      this._el_308,
      this._text_309,
      this._text_310,
      this._el_311,
      this._text_312,
      this._text_313,
      this._el_314,
      this._text_315,
      this._text_316,
      this._text_317,
      this._el_318,
      this._text_319,
      this._el_320,
      this._text_321,
      this._el_322,
      this._text_323,
      this._text_324,
      this._text_325,
      this._text_326,
      this._text_327,
      this._el_328,
      this._text_329,
      this._el_330,
      this._text_331,
      this._el_332,
      this._text_333,
      this._el_334,
      this._text_335,
      this._el_336,
      this._text_337,
      this._text_338,
      this._el_339,
      this._text_340,
      this._text_341,
      this._el_342,
      this._text_343,
      this._text_344,
      this._text_345,
      this._el_346,
      this._text_347,
      this._el_348,
      this._text_349,
      this._el_350,
      this._text_351,
      this._text_352,
      this._text_353,
      this._text_354,
      this._text_355,
      this._text_356,
      this._text_357
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 357)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushvideoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_72_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoHotListPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_80_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_100_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_120_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('/Users/apple/Desktop/github/cfdk/.tmp/pages/home/home.html',0,import10.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}