/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/content/content';
import * as import12 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import13 from 'ionic-angular/config/config';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from 'ionic-angular/components/app/app';
import * as import16 from 'ionic-angular/util/keyboard';
import * as import17 from '@angular/core/src/zone/ng_zone';
import * as import18 from 'ionic-angular/navigation/view-controller';
import * as import19 from 'ionic-angular/components/tabs/tabs';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import10.ComponentFactory<import3.HomePage> = new import10.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import11.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import12.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import11.Content(this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import15.App),this.parentInjector.get(import16.Keyboard),this.parentInjector.get(import17.NgZone),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import19.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'section',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','home-page');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','swiper-container');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','swiper-wrapper');
    this._text_7 = this.renderer.createText(this._el_6,'\n\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','swiper-slide');
    this._text_9 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'img',(null as any));
    this.renderer.setElementAttribute(this._el_10,'src','assets/img2/home_banner_1.jpeg');
    this._text_11 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','swiper-slide');
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'img',(null as any));
    this.renderer.setElementAttribute(this._el_15,'src','assets/img2/home_banner_2.jpeg');
    this._text_16 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','swiper-slide');
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'img',(null as any));
    this.renderer.setElementAttribute(this._el_20,'src','assets/img2/home_banner_3.jpeg');
    this._text_21 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','swiper-slide');
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'img',(null as any));
    this.renderer.setElementAttribute(this._el_25,'src','assets/img2/home_banner_4.jpeg');
    this._text_26 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','swiper-pagination');
    this._text_31 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_2,'section',(null as any));
    this.renderer.setElementAttribute(this._el_33,'id','home_menu');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','home_menu_list');
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'img',(null as any));
    this.renderer.setElementAttribute(this._el_37,'src','assets/icon/home/m1.png');
    this._text_38 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_35,'p',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'菜谱分类',(null as any));
    this._text_41 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','home_menu_list');
    this._text_44 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'img',(null as any));
    this.renderer.setElementAttribute(this._el_45,'src','assets/icon/home/m2.png');
    this._text_46 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_43,'p',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'视频',(null as any));
    this._text_49 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._text_50 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','home_menu_list');
    this._text_52 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'img',(null as any));
    this.renderer.setElementAttribute(this._el_53,'src','assets/icon/home/m3.png');
    this._text_54 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_51,'p',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'养生头条',(null as any));
    this._text_57 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._text_58 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','home_menu_list');
    this._text_60 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'img',(null as any));
    this.renderer.setElementAttribute(this._el_61,'src','assets/icon/home/m4.png');
    this._text_62 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_59,'p',(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'工具分类',(null as any));
    this._text_65 = this.renderer.createText(this._el_59,'\n            ',(null as any));
    this._text_66 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_67 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_68 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_68
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.ngOnDestroy();
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('/Users/apple/Desktop/github/cfdk/.tmp/pages/home/home.html',0,import9.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}