/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './share';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from '@angular/forms/src/directives/ng_model';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from 'ionic-angular/components/segment/segment';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/common/src/directives/ng_switch';
import * as import17 from 'ionic-angular/components/content/content';
import * as import18 from 'ionic-angular/config/config';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from 'ionic-angular/navigation/view-controller';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/forms/src/directives/ng_control';
var renderType_SharePage_Host:import0.RenderComponentType = (null as any);
class _View_SharePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SharePage_0_4:import3.SharePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SharePage_Host0,renderType_SharePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-share',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SharePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SharePage_0_4 = new import3.SharePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._SharePage_0_4,[],compView_0);
    compView_0.create(this._SharePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SharePage) && (0 === requestNodeIndex))) { return this._SharePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SharePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SharePage_Host === (null as any))) { (renderType_SharePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_SharePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SharePageNgFactory:import10.ComponentFactory<import3.SharePage> = new import10.ComponentFactory<import3.SharePage>('page-share',viewFactory_SharePage_Host0,import3.SharePage);
const styles_SharePage:any[] = [];
var renderType_SharePage:import0.RenderComponentType = (null as any);
class _View_SharePage0 extends import1.AppView<import3.SharePage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Toolbar_2_4:import11.Toolbar;
  _text_3:any;
  _el_4:any;
  _NgModel_4_3:import12.NgModel;
  _NgControl_4_4:any;
  _NgControlStatus_4_5:import13.NgControlStatus;
  _Segment_4_6:import14.Segment;
  _query_SegmentButton_4_0:import15.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _SegmentButton_6_4:import14.SegmentButton;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _SegmentButton_9_4:import14.SegmentButton;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _SegmentButton_12_4:import14.SegmentButton;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _NgSwitch_18_4:import16.NgSwitch;
  _Content_18_5:import17.Content;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _TemplateRef_20_5:any;
  _NgSwitchCase_20_6:import16.NgSwitchCase;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgSwitchCase_22_6:import16.NgSwitchCase;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgSwitchCase_24_6:import16.NgSwitchCase;
  _text_25:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SharePage0,renderType_SharePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import20.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','secondary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import21.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import11.Toolbar(this.parentInjector.get(import20.ViewController,(null as any)),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this.renderer.setElementAttribute(this._el_4,'color','fff');
    this._NgModel_4_3 = new import12.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_4_4 = this._NgModel_4_3;
    this._NgControlStatus_4_5 = new import13.NgControlStatus(this._NgControl_4_4);
    this._Segment_4_6 = new import14.Segment(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_4),this.renderer,this._NgControl_4_4);
    this._query_SegmentButton_4_0 = new import15.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','segment-button');
    this.renderer.setElementAttribute(this._el_6,'role','button');
    this.renderer.setElementAttribute(this._el_6,'tappable','');
    this.renderer.setElementAttribute(this._el_6,'value','new1');
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import22.viewFactory_SegmentButton0(this.viewUtils,this.injector(6),this._appEl_6);
    this._SegmentButton_6_4 = new import14.SegmentButton(this.renderer,new import19.ElementRef(this._el_6));
    this._appEl_6.initComponent(this._SegmentButton_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n                厨房问答\n            ',(null as any));
    compView_6.create(this._SegmentButton_6_4,[[].concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','segment-button');
    this.renderer.setElementAttribute(this._el_9,'role','button');
    this.renderer.setElementAttribute(this._el_9,'tappable','');
    this.renderer.setElementAttribute(this._el_9,'value','new2');
    this._appEl_9 = new import2.AppElement(9,4,this,this._el_9);
    var compView_9:any = import22.viewFactory_SegmentButton0(this.viewUtils,this.injector(9),this._appEl_9);
    this._SegmentButton_9_4 = new import14.SegmentButton(this.renderer,new import19.ElementRef(this._el_9));
    this._appEl_9.initComponent(this._SegmentButton_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n                厨房新作\n            ',(null as any));
    compView_9.create(this._SegmentButton_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','segment-button');
    this.renderer.setElementAttribute(this._el_12,'role','button');
    this.renderer.setElementAttribute(this._el_12,'tappable','');
    this.renderer.setElementAttribute(this._el_12,'value','new3');
    this._appEl_12 = new import2.AppElement(12,4,this,this._el_12);
    var compView_12:any = import22.viewFactory_SegmentButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._SegmentButton_12_4 = new import14.SegmentButton(this.renderer,new import19.ElementRef(this._el_12));
    this._appEl_12.initComponent(this._SegmentButton_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n                厨房互动\n            ',(null as any));
    compView_12.create(this._SegmentButton_12_4,[[].concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_15
      ]
      )
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_18 = new import2.AppElement(18,(null as any),this,this._el_18);
    var compView_18:any = import23.viewFactory_Content0(this.viewUtils,this.injector(18),this._appEl_18);
    this._NgSwitch_18_4 = new import16.NgSwitch();
    this._Content_18_5 = new import17.Content(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import24.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import20.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_18.initComponent(this._Content_18_5,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_20 = new import2.AppElement(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import28.TemplateRef_(this._appEl_20,viewFactory_SharePage1);
    this._NgSwitchCase_20_6 = new import16.NgSwitchCase(this._appEl_20.vcRef,this._TemplateRef_20_5,this._NgSwitch_18_4);
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_22 = new import2.AppElement(22,18,this,this._anchor_22);
    this._TemplateRef_22_5 = new import28.TemplateRef_(this._appEl_22,viewFactory_SharePage2);
    this._NgSwitchCase_22_6 = new import16.NgSwitchCase(this._appEl_22.vcRef,this._TemplateRef_22_5,this._NgSwitch_18_4);
    this._text_23 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_24 = new import2.AppElement(24,18,this,this._anchor_24);
    this._TemplateRef_24_5 = new import28.TemplateRef_(this._appEl_24,viewFactory_SharePage3);
    this._NgSwitchCase_24_6 = new import16.NgSwitchCase(this._appEl_24.vcRef,this._TemplateRef_24_5,this._NgSwitch_18_4);
    this._text_25 = this.renderer.createText((null as any),'\n',(null as any));
    compView_18.create(this._Content_18_5,[
      [],
      [].concat([
        this._text_19,
        this._appEl_20,
        this._text_21,
        this._appEl_22,
        this._text_23,
        this._appEl_24,
        this._text_25
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'ngModelChange',this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_4_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._anchor_24,
      this._text_25
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.SegmentButton) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._SegmentButton_6_4; }
    if (((token === import14.SegmentButton) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._SegmentButton_9_4; }
    if (((token === import14.SegmentButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._SegmentButton_12_4; }
    if (((token === import12.NgModel) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgModel_4_3; }
    if (((token === import29.NgControl) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgControl_4_4; }
    if (((token === import13.NgControlStatus) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgControlStatus_4_5; }
    if (((token === import14.Segment) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Segment_4_6; }
    if (((token === import11.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Toolbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Header_0_3; }
    if (((token === import28.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import16.NgSwitchCase) && (20 === requestNodeIndex))) { return this._NgSwitchCase_20_6; }
    if (((token === import28.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import16.NgSwitchCase) && (22 === requestNodeIndex))) { return this._NgSwitchCase_22_6; }
    if (((token === import28.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import16.NgSwitchCase) && (24 === requestNodeIndex))) { return this._NgSwitchCase_24_6; }
    if (((token === import16.NgSwitch) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgSwitch_18_4; }
    if (((token === import17.Content) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Content_18_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Toolbar_2_4.color = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    changes = (null as any);
    const currVal_3:any = this.context.pet;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgModel_4_3.model = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgModel_4_3.ngOnChanges(changes); }
    const currVal_10:any = 'fff';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Segment_4_6.color = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = 'new1';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._SegmentButton_6_4.value = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_6_4.ngOnInit(); }
    const currVal_14:any = 'new2';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._SegmentButton_9_4.value = currVal_14;
      this._expr_14 = currVal_14;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_9_4.ngOnInit(); }
    const currVal_16:any = 'new3';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._SegmentButton_12_4.value = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_12_4.ngOnInit(); }
    const currVal_17:any = this.context.pet;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgSwitch_18_4.ngSwitch = currVal_17;
      this._expr_17 = currVal_17;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_18_5.ngOnInit(); }
    const currVal_19:any = 'new1';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgSwitchCase_20_6.ngSwitchCase = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = 'new2';
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._NgSwitchCase_22_6.ngSwitchCase = currVal_20;
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = 'new3';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgSwitchCase_24_6.ngSwitchCase = currVal_21;
      this._expr_21 = currVal_21;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_SegmentButton_4_0.dirty) {
      this._query_SegmentButton_4_0.reset([
        this._SegmentButton_6_4,
        this._SegmentButton_9_4,
        this._SegmentButton_12_4
      ]
      );
      this._Segment_4_6._buttons = this._query_SegmentButton_4_0;
      this._query_SegmentButton_4_0.notifyOnChanges();
    } }
    const currVal_1:any = this._Toolbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._NgControlStatus_4_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_4,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_4_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_4,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_4_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_4,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_4_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_4,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_4_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_4,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_4_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_4,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_18:any = this._Content_18_5._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_18,'statusbar-padding',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Segment_4_6.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_4_3.ngOnDestroy();
    this._Content_18_5.ngOnDestroy();
  }
  private _handle_ngModelChange_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.pet = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_6_0($event:any):boolean {
    this._appEl_6.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_6_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this._appEl_9.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_9_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_12_4.onClick()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SharePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SharePage> {
  if ((renderType_SharePage === (null as any))) { (renderType_SharePage = viewUtils.createRenderComponentType('/Users/apple/Desktop/github/cfdk/.tmp/pages/share/share.html',0,import9.ViewEncapsulation.None,styles_SharePage,{})); }
  return new _View_SharePage0(viewUtils,parentInjector,declarationEl);
}
class _View_SharePage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _text_129:any;
  _text_130:any;
  _text_131:any;
  _el_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _text_136:any;
  _el_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _el_141:any;
  _text_142:any;
  _text_143:any;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _el_150:any;
  _text_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _text_155:any;
  _text_156:any;
  _text_157:any;
  _el_158:any;
  _text_159:any;
  _el_160:any;
  _text_161:any;
  _text_162:any;
  _el_163:any;
  _text_164:any;
  _el_165:any;
  _text_166:any;
  _el_167:any;
  _text_168:any;
  _text_169:any;
  _text_170:any;
  _el_171:any;
  _text_172:any;
  _text_173:any;
  _el_174:any;
  _text_175:any;
  _el_176:any;
  _text_177:any;
  _text_178:any;
  _el_179:any;
  _text_180:any;
  _text_181:any;
  _text_182:any;
  _text_183:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SharePage1,renderType_SharePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'section',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','qus_wrap');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','qus_list');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'p',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','qus_list_title');
    this._text_5 = this.renderer.createText(this._el_4,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','qus_user_wrap');
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'img',(null as any));
    this.renderer.setElementAttribute(this._el_9,'src','assets/img2/user_2.jpeg');
    this._text_10 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'p',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'毓玲珑',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_2,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_2,'p',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','qus_btm_wrap');
    this._text_19 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'span',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','qus_hd');
    this._text_21 = this.renderer.createText(this._el_20,'0个回答',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'span',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','qus_time');
    this._text_24 = this.renderer.createText(this._el_23,'10-26',(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','qus_list');
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'p',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','qus_list_title');
    this._text_31 = this.renderer.createText(this._el_30,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_28,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','qus_user_wrap');
    this._text_34 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'img',(null as any));
    this.renderer.setElementAttribute(this._el_35,'src','assets/img2/user_1.jpeg');
    this._text_36 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_33,'p',(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'毓玲珑',(null as any));
    this._text_39 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_40 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_28,'p',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_43 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_28,'p',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','qus_btm_wrap');
    this._text_45 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'span',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','qus_hd');
    this._text_47 = this.renderer.createText(this._el_46,'0个回答',(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_44,'span',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','qus_time');
    this._text_50 = this.renderer.createText(this._el_49,'10-26',(null as any));
    this._text_51 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','qus_list');
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'p',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','qus_list_title');
    this._text_57 = this.renderer.createText(this._el_56,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','qus_user_wrap');
    this._text_60 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'img',(null as any));
    this.renderer.setElementAttribute(this._el_61,'src','assets/img2/user_3.jpeg');
    this._text_62 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_59,'p',(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'毓玲珑',(null as any));
    this._text_65 = this.renderer.createText(this._el_59,'\n            ',(null as any));
    this._text_66 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_54,'p',(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_69 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_54,'p',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','qus_btm_wrap');
    this._text_71 = this.renderer.createText(this._el_70,'\n                ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_70,'span',(null as any));
    this.renderer.setElementAttribute(this._el_72,'class','qus_hd');
    this._text_73 = this.renderer.createText(this._el_72,'0个回答',(null as any));
    this._text_74 = this.renderer.createText(this._el_70,'\n                ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_70,'span',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','qus_time');
    this._text_76 = this.renderer.createText(this._el_75,'10-26',(null as any));
    this._text_77 = this.renderer.createText(this._el_70,'\n            ',(null as any));
    this._text_78 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','qus_list');
    this._text_81 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'p',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','qus_list_title');
    this._text_83 = this.renderer.createText(this._el_82,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_84 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_85,'class','qus_user_wrap');
    this._text_86 = this.renderer.createText(this._el_85,'\n                ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_85,'img',(null as any));
    this.renderer.setElementAttribute(this._el_87,'src','assets/img2/user_4.jpeg');
    this._text_88 = this.renderer.createText(this._el_85,'\n                ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_85,'p',(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'毓玲珑',(null as any));
    this._text_91 = this.renderer.createText(this._el_85,'\n            ',(null as any));
    this._text_92 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_80,'p',(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_95 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_80,'p',(null as any));
    this.renderer.setElementAttribute(this._el_96,'class','qus_btm_wrap');
    this._text_97 = this.renderer.createText(this._el_96,'\n                ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_96,'span',(null as any));
    this.renderer.setElementAttribute(this._el_98,'class','qus_hd');
    this._text_99 = this.renderer.createText(this._el_98,'0个回答',(null as any));
    this._text_100 = this.renderer.createText(this._el_96,'\n                ',(null as any));
    this._el_101 = this.renderer.createElement(this._el_96,'span',(null as any));
    this.renderer.setElementAttribute(this._el_101,'class','qus_time');
    this._text_102 = this.renderer.createText(this._el_101,'10-26',(null as any));
    this._text_103 = this.renderer.createText(this._el_96,'\n            ',(null as any));
    this._text_104 = this.renderer.createText(this._el_80,'\n        ',(null as any));
    this._text_105 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_106 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_106,'class','qus_list');
    this._text_107 = this.renderer.createText(this._el_106,'\n            ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_106,'p',(null as any));
    this.renderer.setElementAttribute(this._el_108,'class','qus_list_title');
    this._text_109 = this.renderer.createText(this._el_108,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_110 = this.renderer.createText(this._el_106,'\n            ',(null as any));
    this._el_111 = this.renderer.createElement(this._el_106,'div',(null as any));
    this.renderer.setElementAttribute(this._el_111,'class','qus_user_wrap');
    this._text_112 = this.renderer.createText(this._el_111,'\n                ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_111,'img',(null as any));
    this.renderer.setElementAttribute(this._el_113,'src','assets/img2/user_1.jpeg');
    this._text_114 = this.renderer.createText(this._el_111,'\n                ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_111,'p',(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'毓玲珑',(null as any));
    this._text_117 = this.renderer.createText(this._el_111,'\n            ',(null as any));
    this._text_118 = this.renderer.createText(this._el_106,'\n            ',(null as any));
    this._el_119 = this.renderer.createElement(this._el_106,'p',(null as any));
    this._text_120 = this.renderer.createText(this._el_119,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_121 = this.renderer.createText(this._el_106,'\n            ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_106,'p',(null as any));
    this.renderer.setElementAttribute(this._el_122,'class','qus_btm_wrap');
    this._text_123 = this.renderer.createText(this._el_122,'\n                ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_122,'span',(null as any));
    this.renderer.setElementAttribute(this._el_124,'class','qus_hd');
    this._text_125 = this.renderer.createText(this._el_124,'0个回答',(null as any));
    this._text_126 = this.renderer.createText(this._el_122,'\n                ',(null as any));
    this._el_127 = this.renderer.createElement(this._el_122,'span',(null as any));
    this.renderer.setElementAttribute(this._el_127,'class','qus_time');
    this._text_128 = this.renderer.createText(this._el_127,'10-26',(null as any));
    this._text_129 = this.renderer.createText(this._el_122,'\n            ',(null as any));
    this._text_130 = this.renderer.createText(this._el_106,'\n        ',(null as any));
    this._text_131 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_132 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_132,'class','qus_list');
    this._text_133 = this.renderer.createText(this._el_132,'\n            ',(null as any));
    this._el_134 = this.renderer.createElement(this._el_132,'p',(null as any));
    this.renderer.setElementAttribute(this._el_134,'class','qus_list_title');
    this._text_135 = this.renderer.createText(this._el_134,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_136 = this.renderer.createText(this._el_132,'\n            ',(null as any));
    this._el_137 = this.renderer.createElement(this._el_132,'div',(null as any));
    this.renderer.setElementAttribute(this._el_137,'class','qus_user_wrap');
    this._text_138 = this.renderer.createText(this._el_137,'\n                ',(null as any));
    this._el_139 = this.renderer.createElement(this._el_137,'img',(null as any));
    this.renderer.setElementAttribute(this._el_139,'src','assets/img2/user_3.jpeg');
    this._text_140 = this.renderer.createText(this._el_137,'\n                ',(null as any));
    this._el_141 = this.renderer.createElement(this._el_137,'p',(null as any));
    this._text_142 = this.renderer.createText(this._el_141,'毓玲珑',(null as any));
    this._text_143 = this.renderer.createText(this._el_137,'\n            ',(null as any));
    this._text_144 = this.renderer.createText(this._el_132,'\n            ',(null as any));
    this._el_145 = this.renderer.createElement(this._el_132,'p',(null as any));
    this._text_146 = this.renderer.createText(this._el_145,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_147 = this.renderer.createText(this._el_132,'\n            ',(null as any));
    this._el_148 = this.renderer.createElement(this._el_132,'p',(null as any));
    this.renderer.setElementAttribute(this._el_148,'class','qus_btm_wrap');
    this._text_149 = this.renderer.createText(this._el_148,'\n                ',(null as any));
    this._el_150 = this.renderer.createElement(this._el_148,'span',(null as any));
    this.renderer.setElementAttribute(this._el_150,'class','qus_hd');
    this._text_151 = this.renderer.createText(this._el_150,'0个回答',(null as any));
    this._text_152 = this.renderer.createText(this._el_148,'\n                ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_148,'span',(null as any));
    this.renderer.setElementAttribute(this._el_153,'class','qus_time');
    this._text_154 = this.renderer.createText(this._el_153,'10-26',(null as any));
    this._text_155 = this.renderer.createText(this._el_148,'\n            ',(null as any));
    this._text_156 = this.renderer.createText(this._el_132,'\n        ',(null as any));
    this._text_157 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_158 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_158,'class','qus_list');
    this._text_159 = this.renderer.createText(this._el_158,'\n            ',(null as any));
    this._el_160 = this.renderer.createElement(this._el_158,'p',(null as any));
    this.renderer.setElementAttribute(this._el_160,'class','qus_list_title');
    this._text_161 = this.renderer.createText(this._el_160,'如何炸出kfc和m记的薯条？',(null as any));
    this._text_162 = this.renderer.createText(this._el_158,'\n            ',(null as any));
    this._el_163 = this.renderer.createElement(this._el_158,'div',(null as any));
    this.renderer.setElementAttribute(this._el_163,'class','qus_user_wrap');
    this._text_164 = this.renderer.createText(this._el_163,'\n                ',(null as any));
    this._el_165 = this.renderer.createElement(this._el_163,'img',(null as any));
    this.renderer.setElementAttribute(this._el_165,'src','assets/img2/user_4.jpeg');
    this._text_166 = this.renderer.createText(this._el_163,'\n                ',(null as any));
    this._el_167 = this.renderer.createElement(this._el_163,'p',(null as any));
    this._text_168 = this.renderer.createText(this._el_167,'毓玲珑',(null as any));
    this._text_169 = this.renderer.createText(this._el_163,'\n            ',(null as any));
    this._text_170 = this.renderer.createText(this._el_158,'\n            ',(null as any));
    this._el_171 = this.renderer.createElement(this._el_158,'p',(null as any));
    this._text_172 = this.renderer.createText(this._el_171,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用这是一个简单的菜。闲时腌，忙时十分钟就',(null as any));
    this._text_173 = this.renderer.createText(this._el_158,'\n            ',(null as any));
    this._el_174 = this.renderer.createElement(this._el_158,'p',(null as any));
    this.renderer.setElementAttribute(this._el_174,'class','qus_btm_wrap');
    this._text_175 = this.renderer.createText(this._el_174,'\n                ',(null as any));
    this._el_176 = this.renderer.createElement(this._el_174,'span',(null as any));
    this.renderer.setElementAttribute(this._el_176,'class','qus_hd');
    this._text_177 = this.renderer.createText(this._el_176,'0个回答',(null as any));
    this._text_178 = this.renderer.createText(this._el_174,'\n                ',(null as any));
    this._el_179 = this.renderer.createElement(this._el_174,'span',(null as any));
    this.renderer.setElementAttribute(this._el_179,'class','qus_time');
    this._text_180 = this.renderer.createText(this._el_179,'10-26',(null as any));
    this._text_181 = this.renderer.createText(this._el_174,'\n            ',(null as any));
    this._text_182 = this.renderer.createText(this._el_158,'\n        ',(null as any));
    this._text_183 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._text_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._text_136,
      this._el_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._text_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._el_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._text_155,
      this._text_156,
      this._text_157,
      this._el_158,
      this._text_159,
      this._el_160,
      this._text_161,
      this._text_162,
      this._el_163,
      this._text_164,
      this._el_165,
      this._text_166,
      this._el_167,
      this._text_168,
      this._text_169,
      this._text_170,
      this._el_171,
      this._text_172,
      this._text_173,
      this._el_174,
      this._text_175,
      this._el_176,
      this._text_177,
      this._text_178,
      this._el_179,
      this._text_180,
      this._text_181,
      this._text_182,
      this._text_183
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SharePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SharePage1(viewUtils,parentInjector,declarationEl);
}
class _View_SharePage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _text_113:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SharePage2,renderType_SharePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'section',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','home_works');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','home_work_list');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'src','assets/img2/home_work_1.jpeg');
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','home_work_cont');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','home_work_cont_left');
    this._text_9 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'p',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','home_work_cont_left_title');
    this._text_11 = this.renderer.createText(this._el_10,'蚝油鸡胸肉',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'10-22',(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','home_work_cont_right');
    this._text_21 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'img',(null as any));
    this.renderer.setElementAttribute(this._el_22,'src','assets/img2/user_4.jpeg');
    this._text_23 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_20,'p',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'春燕_Lsg6',(null as any));
    this._text_26 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','home_work_list');
    this._text_31 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'img',(null as any));
    this.renderer.setElementAttribute(this._el_32,'src','assets/img2/home_work_2.jpeg');
    this._text_33 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_30,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','home_work_cont');
    this._text_35 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','home_work_cont_left');
    this._text_37 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'p',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','home_work_cont_left_title');
    this._text_39 = this.renderer.createText(this._el_38,'蚝油鸡胸肉',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_36,'p',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_36,'p',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'10-22',(null as any));
    this._text_46 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','home_work_cont_right');
    this._text_49 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'img',(null as any));
    this.renderer.setElementAttribute(this._el_50,'src','assets/img2/user_3.jpeg');
    this._text_51 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_48,'p',(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'徐徐徐萌萌',(null as any));
    this._text_54 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','home_work_list');
    this._text_59 = this.renderer.createText(this._el_58,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'img',(null as any));
    this.renderer.setElementAttribute(this._el_60,'src','assets/img2/home_work_3.jpeg');
    this._text_61 = this.renderer.createText(this._el_58,'\n            ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_58,'div',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','home_work_cont');
    this._text_63 = this.renderer.createText(this._el_62,'\n                ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_62,'div',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','home_work_cont_left');
    this._text_65 = this.renderer.createText(this._el_64,'\n                    ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'p',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','home_work_cont_left_title');
    this._text_67 = this.renderer.createText(this._el_66,'蚝油鸡胸肉',(null as any));
    this._text_68 = this.renderer.createText(this._el_64,'\n                    ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_64,'p',(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_71 = this.renderer.createText(this._el_64,'\n                    ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_64,'p',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'10-22',(null as any));
    this._text_74 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._text_75 = this.renderer.createText(this._el_62,'\n                ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_62,'div',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','home_work_cont_right');
    this._text_77 = this.renderer.createText(this._el_76,'\n                    ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_76,'img',(null as any));
    this.renderer.setElementAttribute(this._el_78,'src','assets/img2/user_2.jpeg');
    this._text_79 = this.renderer.createText(this._el_76,'\n                    ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_76,'p',(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'毓玲珑',(null as any));
    this._text_82 = this.renderer.createText(this._el_76,'\n                ',(null as any));
    this._text_83 = this.renderer.createText(this._el_62,'\n            ',(null as any));
    this._text_84 = this.renderer.createText(this._el_58,'\n        ',(null as any));
    this._text_85 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_86,'class','home_work_list');
    this._text_87 = this.renderer.createText(this._el_86,'\n            ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_86,'img',(null as any));
    this.renderer.setElementAttribute(this._el_88,'src','assets/img2/home_work_1.jpeg');
    this._text_89 = this.renderer.createText(this._el_86,'\n            ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_86,'div',(null as any));
    this.renderer.setElementAttribute(this._el_90,'class','home_work_cont');
    this._text_91 = this.renderer.createText(this._el_90,'\n                ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'div',(null as any));
    this.renderer.setElementAttribute(this._el_92,'class','home_work_cont_left');
    this._text_93 = this.renderer.createText(this._el_92,'\n                    ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_92,'p',(null as any));
    this.renderer.setElementAttribute(this._el_94,'class','home_work_cont_left_title');
    this._text_95 = this.renderer.createText(this._el_94,'蚝油鸡胸肉',(null as any));
    this._text_96 = this.renderer.createText(this._el_92,'\n                    ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_92,'p',(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'这是一个简单的菜。闲时腌，忙时十分钟就可以吃，而且不用...',(null as any));
    this._text_99 = this.renderer.createText(this._el_92,'\n                    ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_92,'p',(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'10-22',(null as any));
    this._text_102 = this.renderer.createText(this._el_92,'\n                ',(null as any));
    this._text_103 = this.renderer.createText(this._el_90,'\n                ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_90,'div',(null as any));
    this.renderer.setElementAttribute(this._el_104,'class','home_work_cont_right');
    this._text_105 = this.renderer.createText(this._el_104,'\n                    ',(null as any));
    this._el_106 = this.renderer.createElement(this._el_104,'img',(null as any));
    this.renderer.setElementAttribute(this._el_106,'src','assets/img2/user_1.jpeg');
    this._text_107 = this.renderer.createText(this._el_104,'\n                    ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_104,'p',(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'萧冰xiaobing',(null as any));
    this._text_110 = this.renderer.createText(this._el_104,'\n                ',(null as any));
    this._text_111 = this.renderer.createText(this._el_90,'\n            ',(null as any));
    this._text_112 = this.renderer.createText(this._el_86,'\n        ',(null as any));
    this._text_113 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._text_113
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SharePage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SharePage2(viewUtils,parentInjector,declarationEl);
}
class _View_SharePage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SharePage3,renderType_SharePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'section',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'3',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SharePage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SharePage3(viewUtils,parentInjector,declarationEl);
}