/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './toutiaoHotList';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/navigation/view-controller';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from 'ionic-angular/components/app/app';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/components/tabs/tabs';
var renderType_toutiaoHotListPage_Host:import0.RenderComponentType = (null as any);
class _View_toutiaoHotListPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _toutiaoHotListPage_0_4:import3.toutiaoHotListPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_toutiaoHotListPage_Host0,renderType_toutiaoHotListPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-toutiaoHotList',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_toutiaoHotListPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._toutiaoHotListPage_0_4 = new import3.toutiaoHotListPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._toutiaoHotListPage_0_4,[],compView_0);
    compView_0.create(this._toutiaoHotListPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.toutiaoHotListPage) && (0 === requestNodeIndex))) { return this._toutiaoHotListPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_toutiaoHotListPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_toutiaoHotListPage_Host === (null as any))) { (renderType_toutiaoHotListPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_toutiaoHotListPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const toutiaoHotListPageNgFactory:import10.ComponentFactory<import3.toutiaoHotListPage> = new import10.ComponentFactory<import3.toutiaoHotListPage>('page-toutiaoHotList',viewFactory_toutiaoHotListPage_Host0,import3.toutiaoHotListPage);
const styles_toutiaoHotListPage:any[] = [];
var renderType_toutiaoHotListPage:import0.RenderComponentType = (null as any);
class _View_toutiaoHotListPage0 extends import1.AppView<import3.toutiaoHotListPage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import13.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import14.Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _text_127:any;
  _el_128:any;
  _text_129:any;
  _text_130:any;
  _text_131:any;
  _text_132:any;
  _el_133:any;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _el_137:any;
  _text_138:any;
  _text_139:any;
  _el_140:any;
  _text_141:any;
  _el_142:any;
  _text_143:any;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _text_150:any;
  _text_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _el_155:any;
  _text_156:any;
  _el_157:any;
  _text_158:any;
  _text_159:any;
  _el_160:any;
  _text_161:any;
  _el_162:any;
  _text_163:any;
  _text_164:any;
  _el_165:any;
  _text_166:any;
  _text_167:any;
  _el_168:any;
  _text_169:any;
  _text_170:any;
  _text_171:any;
  _text_172:any;
  _el_173:any;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _el_177:any;
  _text_178:any;
  _text_179:any;
  _el_180:any;
  _text_181:any;
  _el_182:any;
  _text_183:any;
  _text_184:any;
  _el_185:any;
  _text_186:any;
  _text_187:any;
  _el_188:any;
  _text_189:any;
  _text_190:any;
  _text_191:any;
  _text_192:any;
  _text_193:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_toutiaoHotListPage0,renderType_toutiaoHotListPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import17.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','secondary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import19.App),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.ToolbarTitle(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n            热门养生头条\n        ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import21.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Content(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import19.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import24.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'section',(null as any));
    this.renderer.setElementAttribute(this._el_11,'id','toutiaoHotList');
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','home_hot_list');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','home_hot_item_img');
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'img',(null as any));
    this.renderer.setElementAttribute(this._el_17,'src','assets/img2/hot_1.jpeg');
    this._text_18 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','home_hot_item');
    this._text_21 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'p',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','home_hot_item_title');
    this._text_23 = this.renderer.createText(this._el_22,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_20,'p',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'浏览数：100',(null as any));
    this._text_27 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_20,'p',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'10-22',(null as any));
    this._text_30 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','home_hot_list');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','home_hot_item_img');
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'img',(null as any));
    this.renderer.setElementAttribute(this._el_37,'src','assets/img2/hot_2.jpeg');
    this._text_38 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','home_hot_item');
    this._text_41 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'p',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','home_hot_item_title');
    this._text_43 = this.renderer.createText(this._el_42,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_40,'p',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'浏览数：100',(null as any));
    this._text_47 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_40,'p',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'10-22',(null as any));
    this._text_50 = this.renderer.createText(this._el_40,'\n            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','home_hot_list');
    this._text_54 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','home_hot_item_img');
    this._text_56 = this.renderer.createText(this._el_55,'\n                ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'img',(null as any));
    this.renderer.setElementAttribute(this._el_57,'src','assets/img2/hot_3.jpeg');
    this._text_58 = this.renderer.createText(this._el_55,'\n            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','home_hot_item');
    this._text_61 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'p',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','home_hot_item_title');
    this._text_63 = this.renderer.createText(this._el_62,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_64 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_60,'p',(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'浏览数：100',(null as any));
    this._text_67 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_60,'p',(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'10-22',(null as any));
    this._text_70 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._text_71 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._text_72 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','home_hot_list');
    this._text_74 = this.renderer.createText(this._el_73,'\n            ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'div',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','home_hot_item_img');
    this._text_76 = this.renderer.createText(this._el_75,'\n                ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_75,'img',(null as any));
    this.renderer.setElementAttribute(this._el_77,'src','assets/img2/hot_1.jpeg');
    this._text_78 = this.renderer.createText(this._el_75,'\n            ',(null as any));
    this._text_79 = this.renderer.createText(this._el_73,'\n            ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_73,'div',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','home_hot_item');
    this._text_81 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'p',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','home_hot_item_title');
    this._text_83 = this.renderer.createText(this._el_82,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_84 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_80,'p',(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'浏览数：100',(null as any));
    this._text_87 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_80,'p',(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'10-22',(null as any));
    this._text_90 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._text_91 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._text_92 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_93,'class','home_hot_list');
    this._text_94 = this.renderer.createText(this._el_93,'\n            ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_93,'div',(null as any));
    this.renderer.setElementAttribute(this._el_95,'class','home_hot_item_img');
    this._text_96 = this.renderer.createText(this._el_95,'\n                ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_95,'img',(null as any));
    this.renderer.setElementAttribute(this._el_97,'src','assets/img2/hot_2.jpeg');
    this._text_98 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._text_99 = this.renderer.createText(this._el_93,'\n            ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_93,'div',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','home_hot_item');
    this._text_101 = this.renderer.createText(this._el_100,'\n                ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_100,'p',(null as any));
    this.renderer.setElementAttribute(this._el_102,'class','home_hot_item_title');
    this._text_103 = this.renderer.createText(this._el_102,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_104 = this.renderer.createText(this._el_100,'\n                ',(null as any));
    this._el_105 = this.renderer.createElement(this._el_100,'p',(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'浏览数：100',(null as any));
    this._text_107 = this.renderer.createText(this._el_100,'\n                ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_100,'p',(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'10-22',(null as any));
    this._text_110 = this.renderer.createText(this._el_100,'\n            ',(null as any));
    this._text_111 = this.renderer.createText(this._el_93,'\n        ',(null as any));
    this._text_112 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_113,'class','home_hot_list');
    this._text_114 = this.renderer.createText(this._el_113,'\n            ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_113,'div',(null as any));
    this.renderer.setElementAttribute(this._el_115,'class','home_hot_item_img');
    this._text_116 = this.renderer.createText(this._el_115,'\n                ',(null as any));
    this._el_117 = this.renderer.createElement(this._el_115,'img',(null as any));
    this.renderer.setElementAttribute(this._el_117,'src','assets/img2/hot_3.jpeg');
    this._text_118 = this.renderer.createText(this._el_115,'\n            ',(null as any));
    this._text_119 = this.renderer.createText(this._el_113,'\n            ',(null as any));
    this._el_120 = this.renderer.createElement(this._el_113,'div',(null as any));
    this.renderer.setElementAttribute(this._el_120,'class','home_hot_item');
    this._text_121 = this.renderer.createText(this._el_120,'\n                ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_120,'p',(null as any));
    this.renderer.setElementAttribute(this._el_122,'class','home_hot_item_title');
    this._text_123 = this.renderer.createText(this._el_122,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_124 = this.renderer.createText(this._el_120,'\n                ',(null as any));
    this._el_125 = this.renderer.createElement(this._el_120,'p',(null as any));
    this._text_126 = this.renderer.createText(this._el_125,'浏览数：100',(null as any));
    this._text_127 = this.renderer.createText(this._el_120,'\n                ',(null as any));
    this._el_128 = this.renderer.createElement(this._el_120,'p',(null as any));
    this._text_129 = this.renderer.createText(this._el_128,'10-22',(null as any));
    this._text_130 = this.renderer.createText(this._el_120,'\n            ',(null as any));
    this._text_131 = this.renderer.createText(this._el_113,'\n        ',(null as any));
    this._text_132 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_133 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_133,'class','home_hot_list');
    this._text_134 = this.renderer.createText(this._el_133,'\n            ',(null as any));
    this._el_135 = this.renderer.createElement(this._el_133,'div',(null as any));
    this.renderer.setElementAttribute(this._el_135,'class','home_hot_item_img');
    this._text_136 = this.renderer.createText(this._el_135,'\n                ',(null as any));
    this._el_137 = this.renderer.createElement(this._el_135,'img',(null as any));
    this.renderer.setElementAttribute(this._el_137,'src','assets/img2/hot_1.jpeg');
    this._text_138 = this.renderer.createText(this._el_135,'\n            ',(null as any));
    this._text_139 = this.renderer.createText(this._el_133,'\n            ',(null as any));
    this._el_140 = this.renderer.createElement(this._el_133,'div',(null as any));
    this.renderer.setElementAttribute(this._el_140,'class','home_hot_item');
    this._text_141 = this.renderer.createText(this._el_140,'\n                ',(null as any));
    this._el_142 = this.renderer.createElement(this._el_140,'p',(null as any));
    this.renderer.setElementAttribute(this._el_142,'class','home_hot_item_title');
    this._text_143 = this.renderer.createText(this._el_142,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_144 = this.renderer.createText(this._el_140,'\n                ',(null as any));
    this._el_145 = this.renderer.createElement(this._el_140,'p',(null as any));
    this._text_146 = this.renderer.createText(this._el_145,'浏览数：100',(null as any));
    this._text_147 = this.renderer.createText(this._el_140,'\n                ',(null as any));
    this._el_148 = this.renderer.createElement(this._el_140,'p',(null as any));
    this._text_149 = this.renderer.createText(this._el_148,'10-22',(null as any));
    this._text_150 = this.renderer.createText(this._el_140,'\n            ',(null as any));
    this._text_151 = this.renderer.createText(this._el_133,'\n        ',(null as any));
    this._text_152 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_153,'class','home_hot_list');
    this._text_154 = this.renderer.createText(this._el_153,'\n            ',(null as any));
    this._el_155 = this.renderer.createElement(this._el_153,'div',(null as any));
    this.renderer.setElementAttribute(this._el_155,'class','home_hot_item_img');
    this._text_156 = this.renderer.createText(this._el_155,'\n                ',(null as any));
    this._el_157 = this.renderer.createElement(this._el_155,'img',(null as any));
    this.renderer.setElementAttribute(this._el_157,'src','assets/img2/hot_2.jpeg');
    this._text_158 = this.renderer.createText(this._el_155,'\n            ',(null as any));
    this._text_159 = this.renderer.createText(this._el_153,'\n            ',(null as any));
    this._el_160 = this.renderer.createElement(this._el_153,'div',(null as any));
    this.renderer.setElementAttribute(this._el_160,'class','home_hot_item');
    this._text_161 = this.renderer.createText(this._el_160,'\n                ',(null as any));
    this._el_162 = this.renderer.createElement(this._el_160,'p',(null as any));
    this.renderer.setElementAttribute(this._el_162,'class','home_hot_item_title');
    this._text_163 = this.renderer.createText(this._el_162,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_164 = this.renderer.createText(this._el_160,'\n                ',(null as any));
    this._el_165 = this.renderer.createElement(this._el_160,'p',(null as any));
    this._text_166 = this.renderer.createText(this._el_165,'浏览数：100',(null as any));
    this._text_167 = this.renderer.createText(this._el_160,'\n                ',(null as any));
    this._el_168 = this.renderer.createElement(this._el_160,'p',(null as any));
    this._text_169 = this.renderer.createText(this._el_168,'10-22',(null as any));
    this._text_170 = this.renderer.createText(this._el_160,'\n            ',(null as any));
    this._text_171 = this.renderer.createText(this._el_153,'\n        ',(null as any));
    this._text_172 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_173 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_173,'class','home_hot_list');
    this._text_174 = this.renderer.createText(this._el_173,'\n            ',(null as any));
    this._el_175 = this.renderer.createElement(this._el_173,'div',(null as any));
    this.renderer.setElementAttribute(this._el_175,'class','home_hot_item_img');
    this._text_176 = this.renderer.createText(this._el_175,'\n                ',(null as any));
    this._el_177 = this.renderer.createElement(this._el_175,'img',(null as any));
    this.renderer.setElementAttribute(this._el_177,'src','assets/img2/hot_3.jpeg');
    this._text_178 = this.renderer.createText(this._el_175,'\n            ',(null as any));
    this._text_179 = this.renderer.createText(this._el_173,'\n            ',(null as any));
    this._el_180 = this.renderer.createElement(this._el_173,'div',(null as any));
    this.renderer.setElementAttribute(this._el_180,'class','home_hot_item');
    this._text_181 = this.renderer.createText(this._el_180,'\n                ',(null as any));
    this._el_182 = this.renderer.createElement(this._el_180,'p',(null as any));
    this.renderer.setElementAttribute(this._el_182,'class','home_hot_item_title');
    this._text_183 = this.renderer.createText(this._el_182,'明日霜降,入冬前养生3注意。',(null as any));
    this._text_184 = this.renderer.createText(this._el_180,'\n                ',(null as any));
    this._el_185 = this.renderer.createElement(this._el_180,'p',(null as any));
    this._text_186 = this.renderer.createText(this._el_185,'浏览数：100',(null as any));
    this._text_187 = this.renderer.createText(this._el_180,'\n                ',(null as any));
    this._el_188 = this.renderer.createElement(this._el_180,'p',(null as any));
    this._text_189 = this.renderer.createText(this._el_188,'10-22',(null as any));
    this._text_190 = this.renderer.createText(this._el_180,'\n            ',(null as any));
    this._text_191 = this.renderer.createText(this._el_173,'\n        ',(null as any));
    this._text_192 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_193 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_193
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_53,'click',this.eventHandler(this._handle_click_53_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_73,'click',this.eventHandler(this._handle_click_73_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_93,'click',this.eventHandler(this._handle_click_93_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_113,'click',this.eventHandler(this._handle_click_113_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_133,'click',this.eventHandler(this._handle_click_133_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_153,'click',this.eventHandler(this._handle_click_153_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_173,'click',this.eventHandler(this._handle_click_173_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._text_127,
      this._el_128,
      this._text_129,
      this._text_130,
      this._text_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._el_137,
      this._text_138,
      this._text_139,
      this._el_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._text_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._text_159,
      this._el_160,
      this._text_161,
      this._el_162,
      this._text_163,
      this._text_164,
      this._el_165,
      this._text_166,
      this._text_167,
      this._el_168,
      this._text_169,
      this._text_170,
      this._text_171,
      this._text_172,
      this._el_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._el_177,
      this._text_178,
      this._text_179,
      this._el_180,
      this._text_181,
      this._el_182,
      this._text_183,
      this._text_184,
      this._el_185,
      this._text_186,
      this._text_187,
      this._el_188,
      this._text_189,
      this._text_190,
      this._text_191,
      this._text_192,
      this._text_193
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import14.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 193)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_53_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_73_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_93_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_113_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_133_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_153_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
  private _handle_click_173_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pushtoutiaoPage()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_toutiaoHotListPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.toutiaoHotListPage> {
  if ((renderType_toutiaoHotListPage === (null as any))) { (renderType_toutiaoHotListPage = viewUtils.createRenderComponentType('/Users/apple/Desktop/github/cfdk/.tmp/pages/toutiaoHotList/toutiaoHotList.html',0,import9.ViewEncapsulation.None,styles_toutiaoHotListPage,{})); }
  return new _View_toutiaoHotListPage0(viewUtils,parentInjector,declarationEl);
}